template: _layouts/layout.erb
bootstrap: _bootstrap.rb
port: 8090

nav:
- education:
    text: Education
    url: education/
- admissions:
    text: Admissions
    url: admissions/
- community:
    text: Community
    url: community/
- about:
    text: About
    url: about/
- contact:
    text: Contact
    url: contact/
